### ISSUE TITLE
Hints don't contain links

### ISSUE THREAD

**Issue by AlexandreSanscartier** [tc-ca/MSS-Seafarer-Certification#49]
The select certificate hint should have two functional links.

**Comment by tc-tibo** [comment]
Fixed it in AB#46325

Commits

- https://github.com/tc-ca/MSS-Seafarer-Certification/commit/d2b7362383eba5011998f5af4608c540f7689ca3

- https://github.com/tc-ca/MSS-Seafarer-Certification/commit/e2b62041e38a563f973b66724f8c192925928f71

PR: #50
